#默认使用配置
spring:
  profiles:
    active: prod
  application:
    name: gohome

server:
  servlet:
    context-path: /gohome
  port: 8080

mybatis:
  typeAliasesPackage: com.hj.tj.gohome.entity
  mapperLocations: classpath:mapper/*.xml

---
#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gohome?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 821075358q
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:logconfig/logback_dev.xml

---
#正式环境
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://cdb-96qh7ip0.cd.tencentcdb.com:10022/gohome?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: huijia931
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:logconfig/logback_pro.xml

---
#测试配置
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://cdb-96qh7ip0.cd.tencentcdb.com:10022/gohome_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: huijia931
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:logconfig/logback_dev.xml